{
  "comments": [
    {
      "unresolved": true,
      "key": {
        "uuid": "b3fcc0e7_84379d54",
        "filename": "/PATCHSET_LEVEL",
        "patchSetId": 17
      },
      "lineNbr": 0,
      "author": {
        "id": 3637389
      },
      "writtenOn": "2024-11-13T08:49:01Z",
      "side": 1,
      "message": "Hi, Has this submission been tested in Windows? We got an error in Windows:\nFile \"F:\\depot_tools\\bootstrap\\bootstrap.py\", line 407, in \u003cmodule\u003e\nsys.exit(main(sys.argv[1:]))\n^^^^^^^^^^^^^^^^^^^^\nFile \"F:\\depot_tools\\bootstrap\\bootstrap.py\", line 373, in main\ngit_dir \u003d search_win_git_directory()\n^^^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"F:\\depot_tools\\bootstrap\\bootstrap.py\", line 281, in search_win_git_directory\nif _within_depot_tools(p):\n^^^^^^^^^^^^^^^^^^^^^^^^^\nFile \"F:\\depot_tools\\bootstrap\\bootstrap.py\", line 251, in _within_depot_tools return os.path.commonpath([os.path.abspath(path), ROOT_DIR]) \u003d\u003d ROOT_DIR ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^ File \"\u003cfrozen ntpath\u003e\", line 826, in commonpath ValueError: Paths don\u0027t have the same drive",
      "revId": "25f97615141aeee8eb168acb09115c6ff16a35f7",
      "serverId": "3ce6091f-6c88-37e8-8c75-72f92ae8dfba"
    }
  ]
}